import { ErrorCode } from "$houdini/graphql/enums";
import type { ValueOf } from "$houdini/runtime/lib/types";

export type UpdateCustomerEmail = {
    readonly "input": UpdateCustomerEmail$input;
    readonly "result": UpdateCustomerEmail$result;
};

export type UpdateCustomerEmail$result = {
    /**
     * Confirm the update of the emailAddress with the provided token, which has been generated by the
    `requestUpdateCustomerEmailAddress` mutation.
    */
    readonly updateCustomerEmailAddress: {
        readonly __typename: string | null;
    } & (({
        readonly errorCode: ValueOf<typeof ErrorCode>;
        readonly message: string;
        readonly __typename: "IdentifierChangeTokenExpiredError";
    }) | ({
        readonly errorCode: ValueOf<typeof ErrorCode>;
        readonly message: string;
        readonly __typename: "IdentifierChangeTokenInvalidError";
    }) | ({
        readonly errorCode: ValueOf<typeof ErrorCode>;
        readonly message: string;
        readonly __typename: "NativeAuthStrategyError";
    }) | ({
        readonly __typename: "non-exhaustive; don't match this";
    }));
};

export type UpdateCustomerEmail$input = {
    token: string;
};

export type UpdateCustomerEmail$optimistic = {
    /**
     * Confirm the update of the emailAddress with the provided token, which has been generated by the
    `requestUpdateCustomerEmailAddress` mutation.
    */
    readonly updateCustomerEmailAddress?: {
        readonly __typename?: string | null;
    } & (({
        readonly errorCode?: ValueOf<typeof ErrorCode>;
        readonly message?: string;
        readonly __typename: "IdentifierChangeTokenExpiredError";
    }) | ({
        readonly errorCode?: ValueOf<typeof ErrorCode>;
        readonly message?: string;
        readonly __typename: "IdentifierChangeTokenInvalidError";
    }) | ({
        readonly errorCode?: ValueOf<typeof ErrorCode>;
        readonly message?: string;
        readonly __typename: "NativeAuthStrategyError";
    }) | ({
        readonly __typename: "non-exhaustive; don't match this";
    }));
};

export type UpdateCustomerEmail$artifact = {
    "name": "UpdateCustomerEmail";
    "kind": "HoudiniMutation";
    "hash": "c9cff5f198885efd916bff3c298b56975fcdd6481ebb4a1476db7558ca2373e8";
    "raw": `mutation UpdateCustomerEmail($token: String!) {
  updateCustomerEmailAddress(token: $token) {
    __typename
    ... on ErrorResult {
      errorCode
      message
    }
    __typename
  }
}
`;
    "rootType": "Mutation";
    "selection": {
        "fields": {
            "updateCustomerEmailAddress": {
                "type": "UpdateCustomerEmailAddressResult";
                "keyRaw": "updateCustomerEmailAddress(token: $token)";
                "selection": {
                    "abstractFields": {
                        "fields": {
                            "ErrorResult": {
                                "errorCode": {
                                    "type": "ErrorCode";
                                    "keyRaw": "errorCode";
                                    "visible": true;
                                };
                                "message": {
                                    "type": "String";
                                    "keyRaw": "message";
                                    "visible": true;
                                };
                                "__typename": {
                                    "type": "String";
                                    "keyRaw": "__typename";
                                    "visible": true;
                                };
                            };
                        };
                        "typeMap": {
                            "IdentifierChangeTokenExpiredError": "ErrorResult";
                            "IdentifierChangeTokenInvalidError": "ErrorResult";
                            "NativeAuthStrategyError": "ErrorResult";
                        };
                    };
                    "fields": {
                        "__typename": {
                            "type": "String";
                            "keyRaw": "__typename";
                            "visible": true;
                        };
                    };
                };
                "abstract": true;
                "visible": true;
            };
        };
    };
    "pluginData": {
        "houdini-svelte": {};
    };
    "input": {
        "fields": {
            "token": "String";
        };
        "types": {};
        "defaults": {};
        "runtimeScalars": {};
    };
};